export type Theme = 'light' | 'dark'
export type Plan = 'free' | 'pro'
export type MuscleGroup = 'chest' | 'back' | 'shoulders' | 'arms' | 'legs' | 'core' | 'cardio' | 'full_body'
export type Equipment = 'barbell' | 'dumbbell' | 'machine' | 'bodyweight' | 'cable' | 'other'
export type Difficulty = 'beginner' | 'intermediate' | 'advanced'
export type ClientGoal = 'weight_loss' | 'muscle_gain' | 'endurance' | 'flexibility' | 'general'
// Legacy types kept for backward-compat with old nutrition features
export type Gender = 'male' | 'female'
export type Goal = 'lose' | 'maintain' | 'gain'
export type MealType = 'breakfast' | 'lunch' | 'dinner' | 'snack'
